### Test /chat POST successful with API key
POST http://localhost:8000/chat
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTc1NjI3ODk1OSwiaWF0IjoxNzU2Mjc4OTU5fQ.x70oOHlVlihRhse7s0hmtrCpitvxJfv8IBtDVEICDro

{
  "messages": [
    {
      "role": "user",
      "content": "What is the overall traffic of my google analytics?"
    }
  ]
}

### Test /chat POST failed without API key
POST http://localhost:8000/chat
Content-Type: application/json

{
  "messages": [
    {
      "role": "user",
      "content": "What is the overall traffic of my google analytics?"
    }
  ]
}
