name: Lint with Ruff

on:
  push:
    branches: ["**"]
    paths:
      - "**.py"
      - "pyproject.toml"
      - ".ruff.toml"
      - "lint.yml"
  pull_request:
    branches: [develop, main]

jobs:
  ruff:
    runs-on: ubuntu-latest
    concurrency:
      group: ruff-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install deps (locked)
        run: uv sync --frozen
      - name: Ruff check
        run: uv run ruff check .
      - name: Ruff format --check
        run: uv run ruff format --check .